export const PUBLIC_CONFIG = {
  // For split deploys, set this in the Netlify-hosted frontend to the EC2 backend origin.
  // Example: "https://api.looi.app". Leave blank for local/same-origin development.
  backendBaseUrl: "",
  maxSpeed: 0.15,
  maxDurationMs: 1000,
  localFirstMode: true,
  localBrainMaxThoughtsPerMinute: 12,
  localBrainServerEnabled: true,
  localBrainProvider: "fireworks",
  localBrainModel: "accounts/fireworks/models/gpt-oss-20b",
  api2dChatEnabled: false,
  api2dChatConfigured: false,
  api2dChatModel: "gpt-4o-mini",
  api2dBrowserVoiceEnabled: false,
  api2dBrowserVoiceLanguage: "zh-CN",
  geminiLiveEnabled: false,
  geminiLiveConfigured: false,
  geminiLiveModel: "gemini-3.1-flash-live-preview",
  geminiLiveVoice: "Kore",
  geminiLiveThinkingLevel: "minimal",
  geminiLiveTransport: "server_relay",
  qwenOmniRealtimeEnabled: false,
  qwenOmniRealtimeConfigured: false,
  qwenOmniRealtimeModel: "qwen3.5-omni-flash-realtime",
  qwenOmniRealtimeVoice: "Ethan",
  qwenOmniRealtimeTransport: "server_relay",
  // DISABLED_ROBOFLOW_FOLLOW: Roboflow config is kept out of the active browser config.
  // roboflowWebrtc: {},
  // roboflowWebrtcProxyUrl: "/api/init-webrtc",
  // roboflowWebrtcTurnConfigUrl: "/api/roboflow-webrtc/turn-config",
  // roboflowWebrtcTerminateUrl: "/api/roboflow-webrtc/terminate",
  geminiVisionAssistDefault: true,
  geminiVisionAssistIntervalMs: 2500,
  // objectDetectionProvider: "roboflow_webrtc",
  // objectDetectorMaxResults: 12,
  // objectDetectorModuleUrl: "/vendor/roboflow-inference-sdk/index.es.js",
  // followLostTimeoutMs: 3000,
  // followTargetCenterX: 0.5,
  // followCenterDeadband: 0.14,
  // followSteerGain: 0.9,
  // maxObjectFollowSpeed: 0.2,
  // followCommandDurationMs: 300,
  // followCommandRefreshMs: 100,
  // followMaxDetectionAgeMs: 300,
  attentionWindowMs: 20000,
  conversationWindowMs: 30000,
  frontendDebugLogging: false,
  localBrainEventCooldownMs: 800,
  performanceMonitorEnabledDefault: true,
  cameraObservationPostMs: 3000,
  cameraSnapshotMaxWidth: 320
};
